// users logged meal entries
import Foundation

struct MealLog: Identifiable{
    let id: UUID
    let date: Date
    let imagePath: String?          // saved photo path on device
    let confirmedPlants: [Plants]   // only matched plants with DB
    var tag: String?                // optional user tag
    var mealInsight: String?        // generated by AI
    
    init(date: Date = .now,
            imagePath: String? = nil,
            confirmedPlants: [Plants],
            tag: String? = nil,
            mealInsight: String? = nil) {
           self.id = UUID()
           self.date = date
           self.imagePath = imagePath
           self.confirmedPlants = confirmedPlants
           self.tag = tag
           self.mealInsight = mealInsight
       }
    
    enum MealCardStyle {
        case compact // square image + short date below
        case gallery // image + time overlaid + optional tag on top left
    }
    
    //total plants per meal
    var totalPlantsInMeal: Int {
        confirmedPlants.count
    }
    //count plants from each group in this meal. for bar chart
    var countPerGroup: [String: Int] {
        var result: [String: Int] = [:]
        for plant in confirmedPlants {
            result[plant.group, default: 0] += 1
        }
        return result
    }
    
    // Full date for detail sheet header e.g. "3:00pm, 11/12/2026"
    var formattedDate: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "h:mma, dd/MM/yyyy"
        return formatter.string(from: date).lowercased()
    }

    // Time only — "3:00 pm"
    var formattedTime: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "h:mm a"
        return formatter.string(from: date).lowercased()
    }

    // Short date — "Wed, 3:00 pm"
    var shortFormattedDate: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "EEE, h:mm a"
        return formatter.string(from: date).lowercased()
    }

    // "Today", "Yesterday", "Saturday"
    var dayLabel: String {
        let calendar = Calendar.current
        if calendar.isDateInToday(date) { return "Today" }
        if calendar.isDateInYesterday(date) { return "Yesterday" }
        let formatter = DateFormatter()
        formatter.dateFormat = "EEEE"
        return formatter.string(from: date)
    }
}
