// users logged meal entries
import Foundation
import SwiftData

@Model
class MealLog: Identifiable{
    var id: UUID
    var date: Date
    var imagePath: String?          // saved photo path on device
    var confirmedPlants: [Plants]   // only matched plants with DB
    var tags: [Tag] = []             // user tag
    var mealInsight: String?        // generated by AI
    
    init(date: Date = .now,
            imagePath: String? = nil,
            confirmedPlants: [Plants],
            tags: [Tag] = [],
            mealInsight: String? = nil) {
           self.id = UUID()
           self.date = date
           self.imagePath = imagePath
           self.confirmedPlants = confirmedPlants
           self.tags = tags
           self.mealInsight = mealInsight
       }
    
    enum MealCardStyle {
        case compact // square image + short date below
        case gallery // image + time overlaid + optional tag on top left
    }
    
    //total plants per meal
    var totalPlantsInMeal: Int {
        confirmedPlants.count
    }
    //count plants from each group in this meal. for bar chart
    var countPerGroup: [String: Int] {
        var result: [String: Int] = [:]
        for plant in confirmedPlants {
            result[plant.group, default: 0] += 1
        }
        return result
    }
    
    // Full date for detail sheet header e.g. "3:00pm, 11/12/2026"
    var formattedDate: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "dd/MM/yyyy, h:mma"
        return formatter.string(from: date).lowercased()
    }

    // Time only — "3:00 pm"
    var formattedTime: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "h:mm a"
        return formatter.string(from: date).lowercased()
    }

    // Short date — "Wed, 3:00 pm"
    var shortFormattedDate: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "EEE, h:mm a"
        return formatter.string(from: date)
    }

    // Grouping key — one entry per calendar day, ignoring time
    var startOfDay: Date {
        Calendar.current.startOfDay(for: date)
    }

    // Section header — "Today", "Yesterday", "Sunday, 26 July", "21 July", "21 July 2025"
    var historyDateLabel: String {
        let calendar = Calendar.current
        if calendar.isDateInToday(date) { return "Today" }
        if calendar.isDateInYesterday(date) { return "Yesterday" }

        let daysAgo = calendar.dateComponents([.day], from: startOfDay, to: calendar.startOfDay(for: .now)).day ?? 0
        let sameYear = calendar.component(.year, from: date) == calendar.component(.year, from: .now)

        let formatter = DateFormatter()
        switch (daysAgo < 7, sameYear) {
        case (true, true):   formatter.dateFormat = "EEEE, d MMMM"
        case (true, false):  formatter.dateFormat = "EEEE, d MMMM yyyy"  // edge case: within a week but crossed a year boundary
        case (false, true):  formatter.dateFormat = "d MMMM"
        case (false, false): formatter.dateFormat = "d MMMM yyyy"
        }
        return formatter.string(from: date)
    }
}
