// users logged meal entries
import Foundation

struct MealLog: Identifiable{
    let id: UUID
    let date: Date
    let imagePath: String?          // saved photo path on device
    let confirmedPlants: [Plants]   // only matched plants with DB
    var tag: String?                // optional user tag
    var mealInsight: String?        // generated by AI
    
    init(date: Date = .now,
            imagePath: String? = nil,
            confirmedPlants: [Plants],
            tag: String? = nil,
            mealInsight: String? = nil) {
           self.id = UUID()
           self.date = date
           self.imagePath = imagePath
           self.confirmedPlants = confirmedPlants
           self.tag = tag
           self.mealInsight = mealInsight
       }
    
    //total plants per meal
    var plantCount: Int {
        confirmedPlants.count
    }
    //count plants from each group in this meal. for bar chart
    var countPerGroup: [String: Int] {
        var result: [String: Int] = [:]
        for plant in confirmedPlants {
            result[plant.group, default: 0] += 1
        }
        return result
    }
 
    // time + date
    var formattedDate: String {
            let formatter = DateFormatter()
            formatter.dateFormat = "h:mma, dd/MM/yyyy"
            return formatter.string(from: date).lowercased()
        }

    
    
}
